[build]
  command = "pip install -r requirements.txt"
  publish = "."  # Changed from "static" - publishes from root
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/student_performance_model.pkl"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
