[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/app.py"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
